In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_excel(r"C:\Users\nihar\Downloads\RFM for Python.xlsx",usecols=["Customer","Date","Amount"])
df

       Customer       Date  Amount
0          4184 2016-09-03      30
1          3657 2018-10-05      34
2          1011 2016-09-18      47
3           106 2015-06-08      94
4           739 2017-06-12      73
...         ...        ...     ...
99995      3511 2017-10-14      76
99996      3939 2016-06-25      99
99997      3262 2018-08-25      77
99998       668 2018-09-22      92
99999      2264 2016-05-02      31

[100000 rows x 3 columns]

In [3]:
today=df["Date"].max()
today

Timestamp('2018-10-06 00:00:00')

In [4]:
#Build R, F, M
rfm=df.groupby("Customer").agg(
    R=("Date", lambda x: (today-x.max()).days),
    F=("Date","count"),
    M=("Amount","sum"),
)
rfm

            R   F     M
Customer
1          61  15   937
2          35  20  1390
3          32  19  1337
4          11  22  1549
5         203  13   792
...       ...  ..   ...
4996       72  17  1242
4997      129  21  1243
4998      410  17   986
4999       13  16   966
5000      294  21  1453

[5000 rows x 3 columns]

In [5]:
#Score 1-5 by quintile
rfm["R_score"]=pd.qcut(rfm["R"],5,labels=[5,4,3,2,1]).astype(int)
rfm["F_score"]=pd.qcut(rfm["R"],5,labels=[1,2,3,4,5]).astype(int)
rfm["M_score"]=pd.qcut(rfm["R"],5,labels=[1,2,3,4,5]).astype(int)
rfm

            R   F     M  R_score  F_score  M_score
Customer
1          61  15   937        3        3        3
2          35  20  1390        4        2        2
3          32  19  1337        4        2        2
4          11  22  1549        5        1        1
5         203  13   792        1        5        5
...       ...  ..   ...      ...      ...      ...
4996       72  17  1242        2        4        4
4997      129  21  1243        1        5        5
4998      410  17   986        1        5        5
4999       13  16   966        5        1        1
5000      294  21  1453        1        5        5

[5000 rows x 6 columns]

In [6]:
rfm["RFM"]=(rfm["R_score"].astype(str)+rfm["F_score"].astype(str)+rfm["M_score"].astype(str))

In [7]:
rfm["Score"]=rfm["R_score"]+rfm["F_score"]+rfm["M_score"]

In [8]:
rfm

            R   F     M  R_score  F_score  M_score  RFM  Score
Customer
1          61  15   937        3        3        3  333      9
2          35  20  1390        4        2        2  422      8
3          32  19  1337        4        2        2  422      8
4          11  22  1549        5        1        1  511      7
5         203  13   792        1        5        5  155     11
...       ...  ..   ...      ...      ...      ...  ...    ...
4996       72  17  1242        2        4        4  244     10
4997      129  21  1243        1        5        5  155     11
4998      410  17   986        1        5        5  155     11
4999       13  16   966        5        1        1  511      7
5000      294  21  1453        1        5        5  155     11

[5000 rows x 8 columns]