In [1]:
import pandas as pd
df=pd.read_excel(r"C:\Users\nihar\Downloads\RFM for Python.xlsx")
df

       Transaction  Customer       Date  Amount
0                1      4184 2016-09-03      30
1                2      3657 2018-10-05      34
2                3      1011 2016-09-18      47
3                4       106 2015-06-08      94
4                5       739 2017-06-12      73
...            ...       ...        ...     ...
99995        99996      3511 2017-10-14      76
99996        99997      3939 2016-06-25      99
99997        99998      3262 2018-08-25      77
99998        99999       668 2018-09-22      92
99999       100000      2264 2016-05-02      31

[100000 rows x 4 columns]

In [2]:
today=df["Date"].max()
today

Timestamp('2018-10-06 00:00:00')

In [3]:
rfm=df.groupby("Customer").agg(
    R=("Date",lambda x: (today-x.max()).days),
    F=("Date","count"),
    M=("Amount","sum"),
)

In [4]:
rfm

            R   F     M
Customer
1          61  15   937
2          35  20  1390
3          32  19  1337
4          11  22  1549
5         203  13   792
...       ...  ..   ...
4996       72  17  1242
4997      129  21  1243
4998      410  17   986
4999       13  16   966
5000      294  21  1453

[5000 rows x 3 columns]

In [5]:
rfm["R_score"]=pd.qcut(rfm["R"],5,labels=[5,4,3,2,1])
rfm["F_score"]=pd.qcut(rfm["R"],5,labels=[1,2,3,4,5])
rfm["M_score"]=pd.qcut(rfm["R"],5,labels=[1,2,3,4,5])

In [6]:
rfm

            R   F     M R_score F_score M_score
Customer
1          61  15   937       3       3       3
2          35  20  1390       4       2       2
3          32  19  1337       4       2       2
4          11  22  1549       5       1       1
5         203  13   792       1       5       5
...       ...  ..   ...     ...     ...     ...
4996       72  17  1242       2       4       4
4997      129  21  1243       1       5       5
4998      410  17   986       1       5       5
4999       13  16   966       5       1       1
5000      294  21  1453       1       5       5

[5000 rows x 6 columns]

In [7]:
rfm.to_excel("RFM for Python.xlsx")
print(rfm.head())

            R   F     M R_score F_score M_score
Customer
1          61  15   937       3       3       3
2          35  20  1390       4       2       2
3          32  19  1337       4       2       2
4          11  22  1549       5       1       1
5         203  13   792       1       5       5